model:
  class_name: twoxplat.model.model.TwoExpertModel

  dim1: 256
  dim2: 512
  dim3: 1024
  num_register_tokens: 4
  head_dim: 64
  inter_multi: 4
  qk_norm: true
  stage1_nlayer: 2
  stage2_nlayer: 4
  stage3_nlayer: 8
  group_size: 2
  patch_size: 4
  in_channels: 12

  gaussians:
    sh_degree: 1
    opacity_degree: 2
    near_plane: 0.01
    far_plane: 1000000.0
    scale_bias: -6.9
    scale_max: -1.2
    opacity_bias: -2.0
    align_to_pixel: true
    max_dist: 500.0

  da_model_name: da3-giant
  da_model_weights_path: pretrained_weights/da3_giant.safetensors
  mvp_weights_path: pretrained_weights/mvp_dl3dv_lr.pt

data:
  data_path: twoxplat/data/dl3dv_train.txt
  input_frame_select_type: uniform
  target_frame_select_type: random
  target_has_input: true
  shuffle_input_prob: 0.0
  reverse_input_prob: 0.5
  square_crop: true
  scene_scale: 1.0
  seed: 777 
  resize_h: 224
  resize_w: 224

training:
  use_amp: true
  use_tf32: true
  amp_dtype: bf16
  
  api_key_path: twoxplat/configs/api_keys.yaml
  num_views: [6, 12, 24, 32] 
  target_views: [6, 6, 6, 1]
  batch_size_per_gpu: [4, 2, 1, 1]
  res_dict:
    - [224, 224]
    - [224, 224]
    - [224, 224]
    - [224, 224]
    
  warmup: 0 
  weight_decay: 0.05
  beta1: 0.9
  beta2: 0.95
  lr: 0.00002
  train_steps: 5000

  checkpoint_dir: experiments/training/2xplat_dl3dv_lr
  checkpoint_every: 1000
  grad_accum_steps: 1
  grad_checkpoint_every: 1
  grad_clip_norm: 1.0

  l2_loss_weight: 1.0
  lpips_loss_weight: 0.0
  perceptual_loss_weight: 0.2
  trans_loss_weight: 10
  rot_loss_weight: 0.1
  intrinsics_loss_weight: 0.5

  num_threads: 8
  num_workers: 4
  prefetch_factor: 8
  print_every: 20

  wandb_project: 2Xplat
  wandb_exp_name: 2xplat_dl3dv_lr
  wandb_log_every: 50
  